### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by Sudha247** [MisterDA/ocaml-swagger#1]
Listing down the items need to be addressed below:

- [x] Ensure `fixes` branch generates the same code as before.
- [x] Add GitHub Actions job to test the generated code compiles.

- [ ] find out missing OpenAPI 2 features.
  + [ ] support `allOf` property of the Schema Object;
  + [ ] account for `collectionFormat`.

@MisterDA: please feel free to add more items.
